<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<ul>
    <li>
        <a href="<?= $escaper->escapeHtmlAttr(
            $block->getUrl('viacheslavv-controller-demos/foobar_responsedemo/redirectresponsedemo')
        ) ?>"
           target="_blank"><?= $escaper->escapeHtml(__('RedirectResponseDemo')) ?></a>
    </li>
    <li>
        <a href="<?= $escaper->escapeHtmlAttr(
            $block->getUrl(
                'viacheslavv-controller-demos/foobar_responsedemo/resultsresponsedemo',
                ['vendor_name' => 'ViacheslavV', 'module_name' => 'ControllerDemos']
            )
        ) ?>">
            <?= $escaper->escapeHtml(__('JsonResponseDemo')) ?>
        </a>
    </li>
    <li>
        <a href="<?= $escaper->escapeHtmlAttr(
            $block->getUrl('viacheslavv-controller-demos/foobar_responsedemo/forwardresponsedemo', [
            'vendor_name' => 'ViacheslavV', 'module_name' => 'ControllerDemos'])
        ) ?>">
            <?= $escaper->escapeHtml(__('ForwardResponseDemo')) ?>
        </a>
    </li>
</ul>
<form method="GET"
      action="<?= $escaper->escapeHtmlAttr(
          $block->getUrl('viacheslavv-controller-demos/foobar_responsedemo/resultsresponsedemo')
      ) ?>">
    <label>
        <input type="text" name="vendor_name" value="ViacheslavV">
    </label><br><br>
    <label>
        <input type="text" name="module_name" value="ControllerDemos">
    </label><br><br>
    <button type="submit"><?= $escaper->escapeHtml(__('Send')) ?></button>
</form>
